### PR TITLE
Fixes #131

### LINKED ISSUE #131: c2nim generates incorrect importc for struct
Given issue https://github.com/nim-lang/Nim/issues/7900, per Araq, the issue is with c2nim.

The importc generated for a `struct` should be:

```
type
  abc {.importc: "struct abc", header: headerfile, bycopy.} = object
```

instead of

```
type
  abc {.importc: "abc", header: headerfile, bycopy.} = object
```

### PR DESCRIPTION
**Pull request by nc-x**

### CODE REVIEW

File: cparse.nim [hunk 1]
```diff
@@ -714,7 +714,7 @@ proc structPragmas(p: Parser, name: PNode, origName: string): PNode =
   #addSon(pragmas, newIdentNodeP("pure", p), newIdentNodeP("final", p))
   if p.options.useHeader:
     addSon(pragmas,
-      newIdentStrLitPair(p.options.importcLit, p.currentNamespace & origName, p),
+      newIdentStrLitPair(p.options.importcLit, "struct " & p.currentNamespace & origName, p),
```
Comment (Araq) [inline cparse.nim]: This should only be done if we are not in CPP mode.

Comment (nc-x) [reply cparse.nim]: https://github.com/nim-lang/Nim/issues/7900 fails on CPP mode if I remove this patch. CPP mode works fine with both `struct` and `class`, i.e. if I tested it correctly.

Comment (Araq) [reply cparse.nim]: It's ugly, C++ doesn't have these silly "struct" prefixes.
